services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # DataFixtures services for test environment
  Tourze\JsonRPCAsyncBundle\DataFixtures\:
    resource: '../../DataFixtures/'
    tags: ['doctrine.fixture.orm']